# Generated by Django 4.1.3 on 2022-11-24 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='mob_number',
            new_name='phone',
        ),
    ]
