# Generated by Django 4.1.2 on 2022-11-28 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_mob_number_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.IntegerField(default=0),
        ),
    ]
